name: cellpose
dependencies:
  - python>3.4
  - pip
  - mkl=2019.3
  - numpy
  - scikit-image
  - numba>=0.43.1
  - pyqt
  - scipy
  - matplotlib
  - pip:
    - mxnet-mkl
    - opencv_python
    - pyqtgraph==0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - cellpose
